### ISSUE TITLE
Security risk

### ISSUE THREAD

**Issue by B3EF** [SofianeHamlaoui/Lockdoor-Framework#19]
Hello, @SofianeHamlaoui - 4 potential high severity security vulnerability in your repository has been disclosed to huntr.
please refer to the report URL and validate them

https://huntr.dev/bounties/9-SofianeHamlaoui/Lockdoor-Framework/
https://huntr.dev/bounties/7-SofianeHamlaoui/Lockdoor-Framework/
https://huntr.dev/bounties/6-SofianeHamlaoui/Lockdoor-Framework/
https://huntr.dev/bounties/8-SofianeHamlaoui/Lockdoor-Framework/

**Comment by SofianeHamlaoui** [comment]
Once again, I won't "login or register" to your website to check them. You can always do a PR.

**Comment by B3EF** [comment]
hi @SofianeHamlaoui first of all, it's not my website I am just an individual  opensource  security researcher, I will not be receiving any bounty if you are not approving my report, so sir please check and validate the reports 
this is my profile of hunr https://huntr.dev/users/b3ef

**Comment by SofianeHamlaoui** [comment]
@B3EF yeah I can approve that without any problem, but I don't want to login to that website.

**Comment by B3EF** [comment]
it just takes only a little time , can you please approve it.

**Comment by JamieSlome** [comment]
I am just going to attach @zidingz from our team and he will be able to help out!

We can send over some magic links if you need them, which will allow you to validate the advisories without signing up to the platform.

**Comment by zidingz** [comment]
Hi @SofianeHamlaoui, glad to help.

Kindly et me know the best way to contact you. I'll share a magic link for each of the vulnerabilities, which will allow you to not only view the report details, but also validate/invalidate the bugs so @B3EF may be rewarded for his efforts.

Let me help you with any questions you have.

Thanks!

**Comment by SofianeHamlaoui** [comment]
@JamieSlome thank's for the suggestion!

**Comment by SofianeHamlaoui** [comment]
@zidingz Hi, 

Yes for sure, last time I joined your platform I didn't stop receiving email and it was really annoying at some point. 

For sure I do respect and love the the effort @B3EF is taking to secure open source projects.

I also do respect your platform and the job you are doing both @JamieSlome and you and the whole team, but unfortunately I don't like registering on too much platforms at least I can know and control the emails I use and my personal info and where I'm usint them.

I like the idea of some magic links it doesn't bother me at all. 


You can contact me on whatever platform you want you can find all my contacts on my personal website [sofianehamlaoui.fr](https://sofianehamlaoui.fr) or just by email [contact@sofianehamlaoui.fr](mailto:contact@sofianehamlaoui.fr)

Have a nice day!

**Comment by zidingz** [comment]
@SofianeHamlaoui We apologise for the spamminess of those emails; we're working on giving maintainers more control over how they are contacted, as well as being more succinct with our communications!

You should receive the magic links in about an hour from now. I've sent them to contact@sofianehamlaoui.fr - simply reply to the emails for further questions. Thank you for your patience and cooperation!

**Comment by SofianeHamlaoui** [comment]
@zidingz perfect I confirmed and validated the 3 ones you sent me, this one isn't validated yet [8-SofianeHamlaoui/Lockdoor-Framework/](https://huntr.dev/bounties/8-SofianeHamlaoui/Lockdoor-Framework/)

@B3EF big thanks for what you are doing ❤️😉

**Comment by B3EF** [comment]
hi @SofianeHamlaoui I have also submitted the patches with the bug report please check that too.
thanks for your effort
