### ISSUE TITLE
Not yet Verified the patches and a remaining command injection bug. 

### ISSUE THREAD

**Issue by B3EF** [SofianeHamlaoui/Lockdoor-Framework#28]
Bugs to be verified
https://www.huntr.dev/bounties/1625101179796-SofianeHamlaoui/Lockdoor-Framework/
https://www.huntr.dev/bounties/8-SofianeHamlaoui/Lockdoor-Framework/

Patches
https://github.com/SofianeHamlaoui/Lockdoor-Framework/compare/HEAD...b3ef:universal-fix
https://github.com/SofianeHamlaoui/Lockdoor-Framework/compare/HEAD...b3ef:master
https://github.com/SofianeHamlaoui/Lockdoor-Framework/compare/HEAD...b3ef:master
https://github.com/SofianeHamlaoui/Lockdoor-Framework/compare/HEAD...b3ef:ci3
https://github.com/SofianeHamlaoui/Lockdoor-Framework/compare/HEAD...b3ef:ci4

**Comment by SofianeHamlaoui** [comment]
@B3EF both are verified, patches needs to be done as PR.

sorry, this week was a long and stressful one, I didn’t have much time to check everything.
