### ISSUE TITLE
Automatic installer deletes all files in /usr/local/bin?

### ISSUE THREAD

**Issue by iwalton3** [SofianeHamlaoui/Lockdoor-Framework#3]
**Describe the bug**
On line 125 of `install.sh`, the command `rm /usr/local/bin/*` will delete all files in the local bin folder. This is probably not desired, as users have probably put other files there.

**To Reproduce**
I did not actually run the installer.

**Expected behavior**
The installer script does not erase the local bin folder.

**Screenshots**
![image](https://user-images.githubusercontent.com/8078788/65285274-fa2db980-db09-11e9-81e0-9ae00fce4efb.png)

**Comment by SofianeHamlaoui** [comment]
That's True ! I did that on my machine as a provisional solution, As I don't have too much time to optimize the tool all by myself,
Thanks for that ! I'm changing that RIGHT NOW ! 
-+
-rm /usr/local/bin/*
+grep -l Sofiane /usr/local/bin/* | xargs rm

**Comment by SofianeHamlaoui** [comment]
If you want to know ( Why Sofiane ) , You can check lockdoor's source code! and you can notice that every file created on /usr/bin/local by lockdoor has a line with this text : (#Dev : Sofiane Hamlaoui).
So thats I used that command to look for the string 'Sofiane' and remove the files contatining that means the files created by lockdoor.
![tex](https://user-images.githubusercontent.com/16967174/65324022-3ebd6180-dbab-11e9-844f-b893b0f36adb.png)
