### ISSUE TITLE
Program launcher doesn't work.

### ISSUE THREAD

**Issue by mehedi0** [SofianeHamlaoui/Lockdoor-Framework#32]
## The problem
Tried multiple times fresh cloning the repo. but after installation process cannot run the program.

## Details
![123456](https://user-images.githubusercontent.com/30646275/134687629-5eea87f9-a00b-4773-bb5a-3709744ce243.png)

 After installation process the command sudo lockdoor doesn't launch the framework. I tried fresh cloning the repository multiple times but the problem is still existed. 
Please check the screenshot attached. I'm excited to use that framework and really appreciate your hard work man. Bless you

## Link to the Logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ logs, and link them here.

**Comment by SofianeHamlaoui** [comment]
Hello @mehedi0,
First of all, how did you install the Lockdoor Framework ? 

And I would like to see the content of the folder /opt/sofiane

Thanks.

**Comment by SofianeHamlaoui** [comment]
If you already have all the files already on the "/opt/sofiane/" folder, try installing it as a python module package ( pip install lockdoor )

**Comment by mehedi0** [comment]
> Hello @mehedi0, First of all, how did you install the Lockdoor Framework ?
> 
> And I would like to see the content of the folder /opt/sofiane
> 
> Thanks.

![Screenshot_20211001_085047](https://user-images.githubusercontent.com/30646275/135623945-64842038-51e3-4f9c-93f1-4969fa236572.png)
![Screenshot_20211001_085417](https://user-images.githubusercontent.com/30646275/135623963-7c803169-a5c8-4e5a-b6c6-2cc9a5ae0243.png)
![Screenshot_20211001_085802](https://user-images.githubusercontent.com/30646275/135623985-ffb652e6-65d1-46da-a2bc-ace3ad193967.png)

![Screenshot_20211001_085917](https://user-images.githubusercontent.com/30646275/135624299-0fbcacab-ce77-4b50-a00d-92498164d14f.png)

I tried all the way so far but no solution. Hope to see a solution soon. As an cybersecurity student I'm super excited to use that framework. Looking forward to getting a positive feedback and really appreciate your work. You may make new installation tutorial for the newest version of Lockdoor.

**Comment by SofianeHamlaoui** [comment]
First of all thanks for the quick answer.

Honestly it’s the first time someone facing this issue, try removing lockdoor using pip ( pip uninstall lockdoor ) and  lunch the installation script again, if the issue still persists I’ll check again the installation script as soon as I have time.

**Comment by SofianeHamlaoui** [comment]
Have you tried running ./lockdoor from the folder directly ?

**Comment by mehedi0** [comment]
> First of all thanks for the quick answer.
> 
> Honestly it’s the first time someone facing this issue, try removing lockdoor using pip ( pip uninstall lockdoor ) and lunch the installation script again, if the issue still persists I’ll check again the installation script as soon as I have time.

It's working now. I tried pip uninstall lockdoor and then reinstalled lockdoor. But there are a few applications are showing error while installing the package, files not found etc. anyway I would try updating the package files and inform you further issues. Thank you bro. I really appreciate your work. Well done. I have an inquiry to you. I'm pretty interested to learn from you as I'm a student of CISSP. Would you please share educational tutorials on Opensource CTI (Cyber Threats Intelligence) Frameworks like **openCTI** Framework ! Thanks again bro

**Comment by SofianeHamlaoui** [comment]
Perfect, I honestly can’t figure out what was the problem exactly. 

For the educational resources and tutorials, you can always contact me on my Twitter so we can have a real conversation and try to help and share with you any kind of resources.

Have a nice day.
