### ISSUE TITLE
Packages removed from Kali Repository Causing Install Failure

### ISSUE THREAD

**Issue by keepittechie** [SofianeHamlaoui/Lockdoor-Framework#33]
**Describe the bug**
Unable to install unsing script "install.sh" because packages have been removed. Python and Netcat. I troubleshot the install script and removed "python", then changed "netcat" to "netcat-traditional" under apt-get package manager.

**To Reproduce**
1. git clone https://github.com/SofianeHamlaoui/Lockdoor-Framework.git
2. cd Lockdoor-Framework
3. sudo chmod +x ./install.sh
4. sudo ./install.sh
5. During the initial dependency install it will state those two packages are unavailable.
6. It will state that the install was completed successfully, but "sudo lockdoor" command is not found.
7. Install doesn't complete

**Expected behavior**
Successful install

**Screenshots**
![lockdoor-f032403](https://user-images.githubusercontent.com/49377875/143730445-ec61cbe7-a02d-4d97-8a48-45466207864d.png)

**Desktop (please complete the following information):**
 - OS: Linux Kali 5.14.0.0-kali4-amd64 #1 SMP Debian 5.14.16-1kali1 (2021-11-05) x86_64 GNU/Linux

**Additional context**
Bug found while recording a video tutorial of the install

**Comment by SofianeHamlaoui** [comment]
Fixed at #36
