### ISSUE TITLE
Command dosen't work.

### ISSUE THREAD

**Issue by theikemaster22** [SofianeHamlaoui/Lockdoor-Framework#37]
I got on my machine today to do some training and realised that the lockdoor command dosen't work, first i got an error saying things about directories so i decided to reinstall it.
Then, after reinstallation i keep just getting a message saying that that command does not exist.
I have not attempted a manual fix and do not plan to 

I am using Kali linux

**To Reproduce**
1. install Lockdoor (i did this by using git clone)
2. make install.sh executeable
3. run install.sh
4. run the lockdoor command

The command dosent work making it so you cant use the Lockdoor Framework

 - OS: Kali linux on docker
 - Version latest (i made this container a couple weeks ago and have been actively updating/upgrading)

**Comment by SofianeHamlaoui** [comment]
I'll update the install script right away, try again and tell me if it's still not working @theikemaster22

**Comment by theikemaster22** [comment]
![image](https://github.com/user-attachments/assets/3ba94d28-ec14-4838-9299-2e71ca2fd8f4)


I am still getting this issue

**Comment by SofianeHamlaoui** [comment]
> ![image](https://private-user-images.githubusercontent.com/151600453/351545280-3ba94d28-ec14-4838-9299-2e71ca2fd8f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4ODcwNDgsIm5iZiI6MTcyMTg4Njc0OCwicGF0aCI6Ii8xNTE2MDA0NTMvMzUxNTQ1MjgwLTNiYTk0ZDI4LWVjMTQtNDgzOC05Mjk5LTJlNzFjYTJmZDhmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNVQwNTUyMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NTk2YjI1NjIzMjNjM2U1MjNkNjI5NWMxMGUzNmI4Zjk1YjU5ZDhlMWYyZDQwOTA0M2U4NzA5YmIzMzZkMzg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.acnwi8o_JDdfUJG5Gv83IIsn4O3L8UVLE5rqBvz8FEA)
> 
> I am still getting this issue

You didn’t pull the changes on github,

> git pull
> ./install.sh
