### ISSUE TITLE
bug isn't fixed

### ISSUE THREAD

**Issue by theikemaster22** [SofianeHamlaoui/Lockdoor-Framework#38]
I am sorry that i didnt respond for a while.
I am in fact still experiencing this issue, the command i am using to get this repo is:
git clone https://github.com/SofianeHamlaoui/Lockdoor-Framework.git
I have 0 idea on why this is occuring i have just found that it thinks the command completely dosent exist.

**Comment by SofianeHamlaoui** [comment]
Can you provide more details about your issue please ? @theikemaster22

**Comment by theikemaster22** [comment]
there isnt much to it on the user side of it, in order to replicate all i did is install it as usual and  it occurs every time, I am using a docker VM of kali linux if that helps.
I might create a new container and see if anything.

after creating a new one i am still experiencing this issue, the command "lockdoor" isnt registered

**Comment by SofianeHamlaoui** [comment]
> there isnt much to it on the user side of it, in order to replicate all i did is install it as usual and it occurs every time, I am using a docker VM of kali linux if that helps. I might create a new container and see if anything.
> 
> after creating a new one i am still experiencing this issue, the command "lockdoor" isnt registered

Hello, 

I think you meant a Docker container ! 

Here are the followed steps that I did following the installation guide on the README file : 

### Installation : 

![image](https://github.com/user-attachments/assets/2f9b8fd7-c061-4c69-a0cd-c5ef394cb0b0)

### Setup : 

![image](https://github.com/user-attachments/assets/66da7d7d-a6bf-4c90-8749-6da589f659fe)


### Running lockdoor : 

![image](https://github.com/user-attachments/assets/6995caeb-be71-4529-94b1-530970128a41)


![image](https://github.com/user-attachments/assets/dd47103a-8f7c-4525-9e2f-ce2e37961d21)


And it's working perfectly ! 

Don't forget, before using it you need to install lockdoor by executing the `./install.sh` script

**Comment by SofianeHamlaoui** [comment]
and here is the full command : 

```bash
git clone https://github.com/SofianeHamlaoui/Lockdoor-Framework.git && cd Lockdoor-Framework && chmod +x ./install.sh && ./install.sh 
```

**Comment by theikemaster22** [comment]
You are correct, i did mean 'docker container' and not 'docker VM', I usually install it how you showed and it still dosen't work, i might just use it on my host machine because it is actually running the same os. I also just tried the install on the host and it works there, I am still confused why docker dosen't like it, i've tried reinstalling, rebooting, and updating and it still dosent work on my docker machines. I will likely just end up using my host machine with ssh.
