### ISSUE TITLE
lockdoor: command not found

### ISSUE THREAD

**Issue by LuongPhuHoa** [SofianeHamlaoui/Lockdoor-Framework#5]
`bash: lockdoor: command not found`

I met this issue after i successfully installed 

But i have no ideas to fix it. Can you help me ? 

Thanks

**Comment by SofianeHamlaoui** [comment]
Lockdoor wasn’t installed completely,
Re install it using this command : 
`bash <(wget -qO- https://lockdoor.sofianehamlaoui.me/lock.html) `
